name       : libgnutls
version    : 3.6.13
release    : 33
source     :
    - https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.13.tar.xz : 32041df447d9f4644570cf573c9f60358e865637d69b7e59d1159b7240b52f38
license    : LGPL-2.1-or-later
component  :
    - security
    - utils : security
summary    :
    - The GnuTLS package contains libraries and userspace tools which provide a secure layer over a reliable transport layer
    - docs : API Documentation for libgnutls
    - utils : Command line applications for GnuTLS
description: |
    GnuTLS is a secure communications library implementing the SSL, TLS and DTLS protocols and technologies around them. It provides a simple C language application programming interface (API) to access the secure communications protocols as well as APIs to parse and write X.509, PKCS #12, OpenPGP and other required structures.
replaces   :
    - utils : gnutls
emul32     : yes
patterns   :
    - docs :
        - /usr/share/gtk-doc
        - /usr/share/info
    - devel :
        - /usr/share/man/man3
    - utils :
        - /usr/bin
        - /usr/share/man/man1
builddeps  :
    - pkgconfig32(autoopts)
    - pkgconfig32(guile-2.0)
    - pkgconfig32(libtasn1)
    - pkgconfig32(nettle)
    - pkgconfig32(p11-kit-1)
    - pkgconfig(gtk-doc)
    - libunistring-32bit-devel
rundeps    :
    - docs : libgnutls-devel
setup      : |
    %configure --disable-static \
        --enable-gtk-doc \
        --htmldir=/usr/share/gtk-doc/html \
        --with-default-trust-store-file=/etc/ssl/certs/ca-certificates.crt
build      : |
    %make
install    : |
    %make_install
